### ISSUE TITLE
keybinding documentation

### ISSUE THREAD

**Issue by boxxxie** [bodil/catnip#15] opened 2012-12-17 18:12 UTC
i use emacs and i did C-k, which worked
C-y didn't work
so i'm wondering what bindings are available :)

**Comment by bodil** [comment] 2012-12-21 15:23
Closing this as a duplicate of #4 (which should make editor bindings self documenting). For now, you can find all editor keybindings in the editor class constructor: https://github.com/bodil/catnip/blob/master/resources/catnip/j/catnip/editor.coffee#L40 - you'll notice there are only two or three in addition to those on the cheat sheet.

**Closed as completed by bodil** 2012-12-21 15:23 UTC
Labels: duplicate
